version: '3.1'
services:
  db:
    image: mysql:5.7.25 # https://hub.docker.com/_/mysql
    restart: always
    ports:
      - 33306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: standard_api
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
